from enum import Enum

class FuelVars(Enum):
    YEAR = 'MODELYEAR'
    MAKE = 'MAKE'
    MODEL = 'MODEL'
    CLASS = 'VEHICLECLASS'
    ENGINE_SIZE = 'ENGINESIZE'
    CYLINDERS = 'CYLINDERS'
    TRANSMISSION = 'TRANSMISSION'
    FUEL_TYPE = 'FUELTYPE'
    CITY = 'FUELCONSUMPTION_CITY'
    HWY = 'FUELCONSUMPTION_HWY'
    COMB = 'FUELCONSUMPTION_COMB'
    COMB_MPG = 'FUELCONSUMPTION_COMB_MPG'
    EMISSIONS = 'CO2EMISSIONS'
